### ISSUE TITLE
commit manually fail

### ISSUE THREAD

**Issue by lijunle** [crawshaw/sqlitejdbc#7]
I set auto commit disable using

``` java
connection.setAutoCommit(false);
```

then, I commit manually

``` java
connection.setAutoCommit(true);
```

but not get it.

``` java
java.sql.SQLException: SQL logic error or missing database
    at org.sqlite.DB.throwex(DB.java:288)
    at org.sqlite.DB.exec(DB.java:68)
    at org.sqlite.Conn.commit(Conn.java:172)
    at database.Database.insert(Database.java:93)
    at junit.DatabaseTest.main(DatabaseTest.java:32)
```

**Comment by lijunle** [comment]
not I am using this project, and it works.
http://www.xerial.org/trac/Xerial/wiki/SQLiteJDBC
